# Generated by Django 3.2.8 on 2024-06-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('lesson_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Dars tartib raqami')),
                ('audio_id', models.CharField(blank=True, max_length=150, verbose_name='Audio ID')),
                ('photo_id', models.CharField(blank=True, max_length=150, verbose_name='Rasm ID')),
                ('video_id', models.CharField(blank=True, max_length=150, verbose_name='Video ID')),
                ('document_id', models.CharField(blank=True, max_length=150, verbose_name='Document ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='Fayl nomi')),
                ('caption', models.TextField(max_length=4000, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Psixoterapiya va psixologiya asoslari',
                'verbose_name_plural': 'Psixoterapiya va psixologiya asoslari',
            },
        ),
        migrations.CreateModel(
            name='Table10',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Tartib raqami')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='Maqola nomi')),
                ('link', models.CharField(max_length=150, null=True, verbose_name='Maqola linki')),
            ],
            options={
                'verbose_name': 'Maqolalar',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('lesson_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Dars tartib raqami')),
                ('audio_id', models.CharField(blank=True, max_length=150, verbose_name='Audio ID')),
                ('photo_id', models.CharField(blank=True, max_length=150, verbose_name='Rasm ID')),
                ('video_id', models.CharField(blank=True, max_length=150, verbose_name='Video ID')),
                ('document_id', models.CharField(blank=True, max_length=150, verbose_name='Document ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='Fayl nomi')),
                ('caption', models.TextField(max_length=4000, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Tabobat va tibbiyotda mijoz va tepmerament ilmi',
                'verbose_name_plural': 'Tabobat va tibbiyotda mijoz va tepmerament ilmi',
            },
        ),
        migrations.CreateModel(
            name='Table3',
            fields=[
                ('lesson_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Dars tartib raqami')),
                ('audio_id', models.CharField(blank=True, max_length=150, verbose_name='Audio ID')),
                ('photo_id', models.CharField(blank=True, max_length=150, verbose_name='Rasm ID')),
                ('video_id', models.CharField(blank=True, max_length=150, verbose_name='Video ID')),
                ('document_id', models.CharField(blank=True, max_length=150, verbose_name='Document ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='Fayl nomi')),
                ('caption', models.TextField(max_length=4000, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Miyaning neyroplastikligi va neyrobika',
                'verbose_name_plural': 'Miyaning neyroplastikligi va neyrobika',
            },
        ),
        migrations.CreateModel(
            name='Table4',
            fields=[
                ('lesson_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Dars tartib raqami')),
                ('audio_id', models.CharField(blank=True, max_length=150, verbose_name='Audio ID')),
                ('photo_id', models.CharField(blank=True, max_length=150, verbose_name='Rasm ID')),
                ('video_id', models.CharField(blank=True, max_length=150, verbose_name='Video ID')),
                ('document_id', models.CharField(blank=True, max_length=150, verbose_name='Document ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='Fayl nomi')),
                ('caption', models.TextField(max_length=4000, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': "Ta'lim va ruhiyat",
                'verbose_name_plural': "Ta'lim va ruhiyat",
            },
        ),
        migrations.CreateModel(
            name='Table5',
            fields=[
                ('lesson_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Dars tartib raqami')),
                ('audio_id', models.CharField(blank=True, max_length=150, verbose_name='Audio ID')),
                ('photo_id', models.CharField(blank=True, max_length=150, verbose_name='Rasm ID')),
                ('video_id', models.CharField(blank=True, max_length=150, verbose_name='Video ID')),
                ('document_id', models.CharField(blank=True, max_length=150, verbose_name='Document ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='Fayl nomi')),
                ('caption', models.TextField(max_length=4000, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Farzandim va jigarbandim',
                'verbose_name_plural': 'Farzandim va jigarbandim',
            },
        ),
        migrations.CreateModel(
            name='Table6',
            fields=[
                ('lesson_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Dars tartib raqami')),
                ('audio_id', models.CharField(blank=True, max_length=150, verbose_name='Audio ID')),
                ('photo_id', models.CharField(blank=True, max_length=150, verbose_name='Rasm ID')),
                ('video_id', models.CharField(blank=True, max_length=150, verbose_name='Video ID')),
                ('document_id', models.CharField(blank=True, max_length=150, verbose_name='Document ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='Fayl nomi')),
                ('caption', models.TextField(max_length=4000, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Nafs diagnostikasi',
                'verbose_name_plural': 'Nafs diagnostikasi',
            },
        ),
        migrations.CreateModel(
            name='Table7',
            fields=[
                ('lesson_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Dars tartib raqami')),
                ('audio_id', models.CharField(blank=True, max_length=150, verbose_name='Audio ID')),
                ('photo_id', models.CharField(blank=True, max_length=150, verbose_name='Rasm ID')),
                ('video_id', models.CharField(blank=True, max_length=150, verbose_name='Video ID')),
                ('document_id', models.CharField(blank=True, max_length=150, verbose_name='Document ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='Fayl nomi')),
                ('caption', models.TextField(max_length=4000, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Sharq psixologiyasi va psixoterapiya',
                'verbose_name_plural': 'Sharq psixologiyasi va psixoterapiya',
            },
        ),
        migrations.CreateModel(
            name='Table8',
            fields=[
                ('lesson_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Dars tartib raqami')),
                ('audio_id', models.CharField(blank=True, max_length=150, verbose_name='Audio ID')),
                ('photo_id', models.CharField(blank=True, max_length=150, verbose_name='Rasm ID')),
                ('video_id', models.CharField(blank=True, max_length=150, verbose_name='Video ID')),
                ('document_id', models.CharField(blank=True, max_length=150, verbose_name='Document ID')),
                ('file_name', models.CharField(max_length=150, null=True, verbose_name='Fayl nomi')),
                ('caption', models.TextField(max_length=4000, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Ruhiy salomatlik',
                'verbose_name_plural': 'Ruhiy salomatlik',
            },
        ),
        migrations.CreateModel(
            name='Table9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='Tartib raqami')),
                ('audio_id', models.CharField(blank=True, max_length=150, verbose_name='Audio ID')),
                ('photo_id', models.CharField(blank=True, max_length=150, verbose_name='Photo ID')),
                ('video_id', models.CharField(blank=True, max_length=150, verbose_name='Video ID')),
                ('voice_id', models.CharField(blank=True, max_length=150, verbose_name='Voice ID')),
                ('document_id', models.CharField(blank=True, max_length=150, verbose_name='Document ID')),
                ('category', models.CharField(max_length=150, null=True, verbose_name='Kategoriya')),
                ('subcategory', models.CharField(max_length=150, null=True, verbose_name='Subkategoriya')),
                ('caption', models.TextField(null=True, verbose_name='Tavsif')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Youtube link')),
            ],
            options={
                'verbose_name': 'Suhbat va loyihalar',
                'verbose_name_plural': 'Suhbat va loyihalar',
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('table_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Tartib raqami:')),
                ('table_name', models.CharField(max_length=200, null=True, verbose_name='Nomi:')),
                ('table_type', models.CharField(max_length=100, null=True, verbose_name='Turi:')),
                ('channel_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Kanal ID raqami:')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izohlar:')),
                ('files', models.BooleanField(default=False, verbose_name="Fayllar yuklangan bo'lsa katakchani belgilab qo'ying")),
            ],
            options={
                'verbose_name': 'Dars va kurslar jadvali',
                'verbose_name_plural': 'Dars va kurslar jadvali',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Telegram username')),
                ('telegram_id', models.BigIntegerField(default=1, unique=True, verbose_name='Telegram ID')),
            ],
        ),
    ]
